In [ ]:
from src.utils import *

fpath = 'rnas.fa'
seqs = readSequences(fpath)
print(seqs)

['UAUUAGGUUGGUGCACAAGUAAUUGCGGUUUUUGCCAAGAAAAGUAAUGGCAAAAACCGCAAUUACUUUUGCACCAGUGUAAUAAUUAGCAUCUUCCGCUAAUCUUUUUC', 'CAUCAAGACCCAGCUGAGUCACUGUCACUGCCUACCAAUCUCGACCGGACCUCGACCGGCUCGUCUGUGUUGCCAAUCGACUCGGCGUGGCGUCGGUCGUGGUAGAUAGGCGGUCAUGCAUACGAAUUUUCAGCUCUUGUUCUGGUGAC']


In [2]:
import numpy as np

class Nussinov: # Secondary Structure Prediction
    def __init__(self, seq, edges, minHairpinLen):
        self.seq = seq
        self.edges = edges
        self.minLoopLen = minHairpinLen
        if minHairpinLen < 1:
            print('minimal Hairpin Loop length must be greater zero. Setting to 1.')
            self.minLoopLen = 1
        

    def tryBasePair(self, i, j):
        if (self.seq[i], self.seq[j]) in self.edges:
            return self.edges[(self.seq[i], self.seq[j])]
        elif (self.seq[j], self.seq[i]) in self.edges:
            return self.edges[(self.seq[j], self.seq[i])]
        else: return 0


    def findSolutionMat(self):
        L = len(self.seq)
        N = np.zeros((L,L), dtype=np.int64) # resembles number of stacked bps
        S = np.zeros_like(N) # encodes Stack Initialization
        for l in range(self.minLoopLen+1,L):
            for i in range(0,L-l):
                j = i + l
                case1 = N[i+1,j-1]
                if (S[i+1,j-1] or N[i+1,j-1]):
                    case1 += self.tryBasePair(i,j)
                cases = [case1, N[i+1,j], N[i,j-1]]
                if l >= 3+2*self.minLoopLen:
                    bifurcMax = np.max([N[i,k]+N[k+1,j] for k in range(i+self.minLoopLen+1, j-self.minLoopLen-1)])
                    cases.append(bifurcMax)
                N[i,j] = np.max(cases)
                
                if i+self.minLoopLen+1==j or N[i+1,j-1] == N[i+2,j-2]: #we have ńo stack
                    S[i,j] = self.tryBasePair(i,j)
        self.N = N
        print(self.N)


    def traceback(self):
        L = len(self.seq)
        N = self.N
        basePairs = []
        connections = '.' * L
        stack = []
        stack.append((0,L-1))
        while len(stack) > 0:
            i,j = stack.pop(0)
            if i+self.minLoopLen < j:
                dij = self.tryBasePair(i,j)
                if ( ( N[i+1,j-1] + dij == N[i,j] ) \
                    or ( i>0 and j<L-1 and N[i-1,j+1] == dij ) ) and dij: # check if Stack begins
                    basePairs.append([i,j])
                    connections = connections[:i] +'(' + connections[i+1:]
                    connections = connections[:j] +')' + connections[j+1:]
                    stack.append((i+1,j-1))
                elif N[i+1,j] == N[i,j]:
                    stack.append((i+1,j))
                elif N[i,j-1] == N[i,j]:
                    stack.append((i,j-1))
                else:
                    for k in range(i+1, j-1):
                        if N[i,k] + N[k+1,j] == N[i,j]:
                            stack.append((i,k))
                            stack.append((k+1,j))
                            break

        return basePairs, connections

In [3]:
# Simple Example:

edges = {('G', 'U'): 1, ('A', 'U'): 2, ('C', 'G'): 3}
seq = 'GGGAAUUU'
nussinov = Nussinov(seq, edges, minHairpinLen=3)
nussinov.findSolutionMat()
basePairs, connections = nussinov.traceback()
print('Base Pairs:', basePairs)
print('Connections:', connections)

[[0 0 0 0 0 0 1 1]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
Base Pairs: [[0, 7], [1, 6]]
Connections: ((....))


In [4]:
# Predict structures of "rnas.fa" sequences:

edges = {('G', 'U'): 1, ('A', 'U'): 2, ('C', 'G'): 3}

connections_all_seqs = []
for i, seq in enumerate(seqs):
    print('Sequence:', seq)
    nussinov = Nussinov(seq, edges, 3)
    nussinov.findSolutionMat()
    basePairs, connections = nussinov.traceback()
    print('Base Pairs:', basePairs)
    print('Connections:', connections)
    connections_all_seqs.append(connections)

Sequence: UAUUAGGUUGGUGCACAAGUAAUUGCGGUUUUUGCCAAGAAAAGUAAUGGCAAAAACCGCAAUUACUUUUGCACCAGUGUAAUAAUUAGCAUCUUCCGCUAAUCUUUUUC
[[ 0  0  0 ... 93 93 93]
 [ 0  0  0 ... 93 93 93]
 [ 0  0  0 ... 91 91 91]
 ...
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]]
Base Pairs: [[1, 108], [4, 107], [5, 106], [6, 103], [7, 101], [8, 100], [9, 98], [10, 73], [74, 97], [11, 72], [12, 71], [13, 70], [75, 94], [14, 69], [76, 92], [16, 68], [17, 67], [77, 90], [78, 89], [18, 65], [19, 64], [79, 87], [20, 63], [80, 86], [21, 62], [81, 85], [22, 61], [23, 60], [24, 59], [25, 58], [26, 57], [27, 56], [28, 55], [29, 54], [30, 53], [31, 52], [32, 51], [33, 50], [34, 49], [35, 48]]
Connections: .(..(((((((((((.((((((((((((((((((((............)))))))))))))))))).)))))))((((((((...))).)).).)..)).)).)..))).
Sequence: CAUCAAGACCCAGCUGAGUCACUGUCACUGCCUACCAAUCUCGACCGGACCUCGACCGGCUCGUCUGUGUUGCCAAUCGACUCGGCGUGGCGUCGGUCGUGGUAGAUAGGCGGUCAUGCAUACGAAUUUUCAGCUCUUGUUCUGGUGAC
[[  0   0   0 ... 137 137 1

In [5]:
# Create plots of predicted structures with draw_ss:

from rna_tools.SecondaryStructure import draw_ss
# https://rna-tools.readthedocs.io/en/latest/tools.html
# https://rna-tools.readthedocs.io/en/latest/install-dev.html#configuration

for i, seq in enumerate(seqs):
    pltFile = f'sndStrImgs/sndStrRNA-{i+1}.png'
    draw_ss('rna', seq, connections_all_seqs[i], pltFile)